import type { ErrorCode, ErrorDefinition } from "./types";

const BASE_URI = "https://minnano-shukin.com/errors";

export const ERROR_REGISTRY: Record<ErrorCode, ErrorDefinition> = {
  // --- 認証・認可 ---
  UNAUTHORIZED: {
    code: "UNAUTHORIZED",
    httpStatus: 401,
    message: "Authentication required",
    userMessage: "認証が必要です。ログインしてから再度お試しください。",
    typeUri: `${BASE_URI}/unauthorized`,
    severity: "medium",
    retryable: false,
    category: "auth",
  },
  FORBIDDEN: {
    code: "FORBIDDEN",
    httpStatus: 403,
    message: "Access denied",
    userMessage: "このリソースにアクセスする権限がありません。",
    typeUri: `${BASE_URI}/forbidden`,
    severity: "medium",
    retryable: false,
    category: "auth",
  },
  TOKEN_INVALID: {
    code: "TOKEN_INVALID",
    httpStatus: 401,
    message: "Token is invalid",
    userMessage: "トークンが無効です。",
    typeUri: `${BASE_URI}/token-invalid`,
    severity: "medium",
    retryable: false,
    category: "auth",
  },
  TOKEN_EXPIRED: {
    code: "TOKEN_EXPIRED",
    httpStatus: 401,
    message: "Token has expired",
    userMessage: "トークンの有効期限が切れています。",
    typeUri: `${BASE_URI}/token-expired`,
    severity: "medium",
    retryable: false,
    category: "auth",
  },
  TOKEN_NOT_FOUND: {
    code: "TOKEN_NOT_FOUND",
    httpStatus: 404,
    message: "Token not found",
    userMessage: "トークンが見つかりません。",
    typeUri: `${BASE_URI}/token-not-found`,
    severity: "medium",
    retryable: false,
    category: "auth",
  },
  GUEST_TOKEN_INVALID: {
    code: "GUEST_TOKEN_INVALID",
    httpStatus: 401,
    message: "Guest token is invalid",
    userMessage: "ゲストトークンが無効です。",
    typeUri: `${BASE_URI}/guest-token-invalid`,
    severity: "medium",
    retryable: false,
    category: "auth",
  },

  GUEST_TOKEN_NOT_FOUND: {
    code: "GUEST_TOKEN_NOT_FOUND",
    httpStatus: 404,
    message: "Guest token not found",
    userMessage: "ゲストトークンが見つかりません。",
    typeUri: `${BASE_URI}/guest-token-not-found`,
    severity: "medium",
    retryable: false,
    category: "auth",
  },
  GUEST_TOKEN_EXPIRED: {
    code: "GUEST_TOKEN_EXPIRED",
    httpStatus: 401,
    message: "Guest token has expired",
    userMessage: "アクセストークンの有効期限が切れています。",
    typeUri: `${BASE_URI}/guest-token-expired`,
    severity: "low",
    retryable: false,
    category: "auth",
  },
  GUEST_TOKEN_VALIDATION_FAILED: {
    code: "GUEST_TOKEN_VALIDATION_FAILED",
    httpStatus: 500,
    message: "Guest token validation failed",
    userMessage: "参加データの取得中にエラーが発生しました。",
    typeUri: `${BASE_URI}/guest-token-validation-failed`,
    severity: "high",
    retryable: true,
    category: "auth",
  },
  INVITE_TOKEN_INVALID: {
    code: "INVITE_TOKEN_INVALID",
    httpStatus: 404,
    message: "Invite token is invalid",
    userMessage: "無効な招待リンクです。",
    typeUri: `${BASE_URI}/invite-token-invalid`,
    severity: "medium",
    retryable: false,
    category: "auth",
  },
  INVITE_TOKEN_NOT_FOUND: {
    code: "INVITE_TOKEN_NOT_FOUND",
    httpStatus: 404,
    message: "Invite token not found",
    userMessage: "招待リンクが見つかりません。",
    typeUri: `${BASE_URI}/invite-token-not-found`,
    severity: "medium",
    retryable: false,
    category: "auth",
  },
  OTP_INVALID: {
    code: "OTP_INVALID",
    httpStatus: 400,
    message: "Invalid OTP",
    userMessage: "確認コードが正しくありません。",
    typeUri: `${BASE_URI}/otp-invalid`,
    severity: "medium",
    retryable: false,
    category: "auth",
  },
  OTP_EXPIRED: {
    code: "OTP_EXPIRED",
    httpStatus: 400,
    message: "OTP has expired",
    userMessage: "確認コードの有効期限が切れています。再送してください。",
    typeUri: `${BASE_URI}/otp-expired`,
    severity: "medium",
    retryable: false,
    category: "auth",
  },
  LOGIN_FAILED: {
    code: "LOGIN_FAILED",
    httpStatus: 401,
    message: "Login failed (invalid credentials)",
    userMessage: "メールアドレスまたはパスワードが正しくありません。",
    typeUri: `${BASE_URI}/login-failed`,
    severity: "medium",
    retryable: false,
    category: "auth",
  },
  // --- Auth Actions (Unexpected) ---
  REGISTRATION_UNEXPECTED_ERROR: {
    code: "REGISTRATION_UNEXPECTED_ERROR",
    httpStatus: 500,
    message: "User registration failed unexpectedly",
    userMessage: "登録処理中にエラーが発生しました。",
    typeUri: `${BASE_URI}/registration-error`,
    severity: "high",
    retryable: true,
    category: "auth",
  },
  LOGIN_UNEXPECTED_ERROR: {
    code: "LOGIN_UNEXPECTED_ERROR",
    httpStatus: 500,
    message: "Login failed unexpectedly",
    userMessage: "ログイン処理中にエラーが発生しました。",
    typeUri: `${BASE_URI}/login-error`,
    severity: "high",
    retryable: true,
    category: "auth",
  },
  OTP_UNEXPECTED_ERROR: {
    code: "OTP_UNEXPECTED_ERROR",
    httpStatus: 500,
    message: "OTP verification failed unexpectedly",
    userMessage: "確認処理中にエラーが発生しました。",
    typeUri: `${BASE_URI}/otp-error`,
    severity: "high",
    retryable: true,
    category: "auth",
  },
  RESEND_OTP_UNEXPECTED_ERROR: {
    code: "RESEND_OTP_UNEXPECTED_ERROR",
    httpStatus: 500,
    message: "OTP resend failed unexpectedly",
    userMessage: "再送信処理中にエラーが発生しました。",
    typeUri: `${BASE_URI}/otp-resend-error`,
    severity: "high",
    retryable: true,
    category: "auth",
  },
  RESET_PASSWORD_UNEXPECTED_ERROR: {
    code: "RESET_PASSWORD_UNEXPECTED_ERROR",
    httpStatus: 500,
    message: "Password reset request failed unexpectedly",
    userMessage: "パスワードリセット処理中にエラーが発生しました。",
    typeUri: `${BASE_URI}/password-reset-error`,
    severity: "high",
    retryable: true,
    category: "auth",
  },
  UPDATE_PASSWORD_UNEXPECTED_ERROR: {
    code: "UPDATE_PASSWORD_UNEXPECTED_ERROR",
    httpStatus: 500,
    message: "Password update failed unexpectedly",
    userMessage: "パスワード更新処理中にエラーが発生しました。",
    typeUri: `${BASE_URI}/password-update-error`,
    severity: "high",
    retryable: true,
    category: "auth",
  },
  LOGOUT_UNEXPECTED_ERROR: {
    code: "LOGOUT_UNEXPECTED_ERROR",
    httpStatus: 500,
    message: "Logout failed unexpectedly",
    userMessage: "ログアウト処理中にエラーが発生しました。",
    typeUri: `${BASE_URI}/logout-error`,
    severity: "medium",
    retryable: false,
    category: "auth",
  },
  PROFILE_UPDATE_UNEXPECTED_ERROR: {
    code: "PROFILE_UPDATE_UNEXPECTED_ERROR",
    httpStatus: 500,
    message: "Profile update failed unexpectedly",
    userMessage: "プロフィールの更新中にエラーが発生しました。",
    typeUri: `${BASE_URI}/profile-update-error`,
    severity: "high",
    retryable: true,
    category: "auth",
  },
  EMAIL_UPDATE_UNEXPECTED_ERROR: {
    code: "EMAIL_UPDATE_UNEXPECTED_ERROR",
    httpStatus: 500,
    message: "Email update failed unexpectedly",
    userMessage: "メールアドレスの更新中にエラーが発生しました。",
    typeUri: `${BASE_URI}/email-update-error`,
    severity: "high",
    retryable: true,
    category: "auth",
  },
  ACCOUNT_DELETION_UNEXPECTED_ERROR: {
    code: "ACCOUNT_DELETION_UNEXPECTED_ERROR",
    httpStatus: 500,
    message: "Account deletion failed unexpectedly",
    userMessage: "退会処理中にエラーが発生しました。",
    typeUri: `${BASE_URI}/account-deletion-error`,
    severity: "high",
    retryable: true,
    category: "auth",
  },

  // --- LINE Login ---
  LINE_LOGIN_ERROR: {
    code: "LINE_LOGIN_ERROR",
    httpStatus: 500,
    message: "LINE login failed unexpectedly",
    userMessage: "LINEログイン処理中にエラーが発生しました。",
    typeUri: `${BASE_URI}/line-login-error`,
    severity: "high",
    retryable: true,
    category: "auth",
  },
  LINE_CSRF_VALIDATION_FAILED: {
    code: "LINE_CSRF_VALIDATION_FAILED",
    httpStatus: 400,
    message: "LINE login CSRF validation failed",
    userMessage: "認証セッションが正しくありません。最初からやり直してください。",
    typeUri: `${BASE_URI}/line-csrf-error`,
    severity: "medium",
    retryable: false,
    category: "auth",
  },
  LINE_TOKEN_RETRIEVAL_FAILED: {
    code: "LINE_TOKEN_RETRIEVAL_FAILED",
    httpStatus: 502,
    message: "Failed to retrieve ID token from LINE",
    userMessage: "LINEからの認証情報の取得に失敗しました。",
    typeUri: `${BASE_URI}/line-token-error`,
    severity: "high",
    retryable: true,
    category: "auth",
  },
  LINE_PROFILE_ERROR: {
    code: "LINE_PROFILE_ERROR",
    httpStatus: 502,
    message: "Failed to retrieve user profile from LINE",
    userMessage: "LINEのプロフィール情報の取得に失敗しました。",
    typeUri: `${BASE_URI}/line-profile-error`,
    severity: "high",
    retryable: true,
    category: "auth",
  },
  LINE_ACCOUNT_LINKING_FAILED: {
    code: "LINE_ACCOUNT_LINKING_FAILED",
    httpStatus: 500,
    message: "Failed to link LINE account",
    userMessage: "LINEアカウントの連携に失敗しました。",
    typeUri: `${BASE_URI}/line-linking-error`,
    severity: "high",
    retryable: true,
    category: "auth",
  },

  // --- 入力・リクエスト ---
  INVALID_REQUEST: {
    code: "INVALID_REQUEST",
    httpStatus: 400,
    message: "Invalid request format",
    userMessage: "リクエストが無効です。",
    typeUri: `${BASE_URI}/invalid-request`,
    severity: "low",
    retryable: false,
    category: "validation",
  },
  METHOD_NOT_ALLOWED: {
    code: "METHOD_NOT_ALLOWED",
    httpStatus: 405,
    message: "Method not allowed",
    userMessage: "許可されていないリクエストメソッドです。",
    typeUri: `${BASE_URI}/method-not-allowed`,
    severity: "low",
    retryable: false,
    category: "validation",
  },
  VALIDATION_ERROR: {
    code: "VALIDATION_ERROR",
    httpStatus: 422,
    message: "Validation failed",
    userMessage: "入力内容に誤りがあります。確認して再度お試しください。",
    typeUri: `${BASE_URI}/validation-error`,
    severity: "low",
    retryable: false,
    category: "validation",
  },
  MISSING_PARAMETER: {
    code: "MISSING_PARAMETER",
    httpStatus: 400,
    message: "Required parameter is missing",
    userMessage: "必要な情報が不足しています。",
    typeUri: `${BASE_URI}/missing-parameter`,
    severity: "low",
    retryable: false,
    category: "validation",
  },
  INVALID_FORMAT: {
    code: "INVALID_FORMAT",
    httpStatus: 400,
    message: "Invalid data format",
    userMessage: "データ形式が正しくありません。",
    typeUri: `${BASE_URI}/invalid-format`,
    severity: "low",
    retryable: false,
    category: "validation",
  },
  INVALID_JSON: {
    code: "INVALID_JSON",
    httpStatus: 400,
    message: "Invalid JSON in request body",
    userMessage: "リクエストの形式が正しくありません。",
    typeUri: `${BASE_URI}/invalid-json`,
    severity: "medium",
    retryable: false,
    category: "validation",
  },

  // --- リソース ---
  NOT_FOUND: {
    code: "NOT_FOUND",
    httpStatus: 404,
    message: "Resource not found",
    userMessage: "お探しのページやデータが見つかりません。",
    typeUri: `${BASE_URI}/not-found`,
    severity: "low",
    retryable: false,
    category: "not-found",
  },
  RESOURCE_CONFLICT: {
    code: "RESOURCE_CONFLICT",
    httpStatus: 409,
    message: "Resource state conflict",
    userMessage: "データの競合が発生しました。画面を更新して再度お試しください。",
    typeUri: `${BASE_URI}/resource-conflict`,
    severity: "medium",
    retryable: true,
    category: "business",
  },
  ALREADY_EXISTS: {
    code: "ALREADY_EXISTS",
    httpStatus: 409,
    message: "Resource already exists",
    userMessage: "既に登録されています。",
    typeUri: `${BASE_URI}/already-exists`,
    severity: "medium",
    retryable: false,
    category: "business",
  },

  // --- イベント ---
  EVENT_NOT_FOUND: {
    code: "EVENT_NOT_FOUND",
    httpStatus: 404,
    message: "Event not found",
    userMessage: "イベントが見つかりません。",
    typeUri: `${BASE_URI}/event-not-found`,
    severity: "medium",
    retryable: false,
    category: "business",
  },
  EVENT_CANCELED: {
    code: "EVENT_CANCELED",
    httpStatus: 410,
    message: "Event has been canceled",
    userMessage: "このイベントはキャンセルされました。",
    typeUri: `${BASE_URI}/event-canceled`,
    severity: "medium",
    retryable: false,
    category: "business",
  },
  EVENT_ENDED: {
    code: "EVENT_ENDED",
    httpStatus: 410,
    message: "Event has ended",
    userMessage: "このイベントは終了しています。",
    typeUri: `${BASE_URI}/event-ended`,
    severity: "medium",
    retryable: false,
    category: "business",
  },
  EVENT_FULL: {
    code: "EVENT_FULL",
    httpStatus: 409,
    message: "Event capacity reached",
    userMessage: "定員に達したため、申し込みを締め切りました。",
    typeUri: `${BASE_URI}/event-full`,
    severity: "medium",
    retryable: false,
    category: "business",
  },
  EVENT_ACCESS_DENIED: {
    code: "EVENT_ACCESS_DENIED",
    httpStatus: 403,
    message: "Event access denied",
    userMessage: "このイベントへのアクセス権限がありません。",
    typeUri: `${BASE_URI}/event-access-denied`,
    severity: "medium",
    retryable: false,
    category: "auth",
  },
  EVENT_DELETE_RESTRICTED: {
    code: "EVENT_DELETE_RESTRICTED",
    httpStatus: 409,
    message: "Cannot delete event with attendees",
    userMessage: "参加者がいるためイベントを削除できません。",
    typeUri: `${BASE_URI}/event-delete-restricted`,
    severity: "medium",
    retryable: false,
    category: "business",
  },
  EVENT_DELETE_FAILED: {
    code: "EVENT_DELETE_FAILED",
    httpStatus: 500,
    message: "Failed to delete event",
    userMessage: "イベントの削除に失敗しました。",
    typeUri: `${BASE_URI}/event-delete-failed`,
    severity: "high",
    retryable: true,
    category: "system",
  },
  EVENT_INVALID_ID: {
    code: "EVENT_INVALID_ID",
    httpStatus: 400,
    message: "Invalid Event ID format",
    userMessage: "無効なイベントID形式です。",
    typeUri: `${BASE_URI}/event-invalid-id`,
    severity: "low",
    retryable: false,
    category: "validation",
  },
  EVENT_OPERATION_FAILED: {
    code: "EVENT_OPERATION_FAILED",
    httpStatus: 500,
    message: "Event operation failed",
    userMessage: "イベント関連の処理でエラーが発生しました。",
    typeUri: `${BASE_URI}/event-operation-failed`,
    severity: "high",
    retryable: true,
    category: "business",
  },
  EVENT_DISPATCH_ERROR: {
    code: "EVENT_DISPATCH_ERROR",
    httpStatus: 500,
    message: "Internal event dispatch failed",
    userMessage: "システム内イベントの配信に失敗しました。",
    typeUri: `${BASE_URI}/event-dispatch-error`,
    severity: "high",
    retryable: true,
    category: "system",
  },

  // --- 参加・登録 ---
  REGISTRATION_CLOSED: {
    code: "REGISTRATION_CLOSED",
    httpStatus: 409,
    message: "Registration is closed",
    userMessage: "申し込み受付は終了しました。",
    typeUri: `${BASE_URI}/registration-closed`,
    severity: "medium",
    retryable: false,
    category: "business",
  },
  REGISTRATION_DEADLINE_PASSED: {
    code: "REGISTRATION_DEADLINE_PASSED",
    httpStatus: 410,
    message: "Registration deadline passed",
    userMessage: "申込期限を過ぎています。",
    typeUri: `${BASE_URI}/registration-deadline-passed`,
    severity: "medium",
    retryable: false,
    category: "business",
  },
  DUPLICATE_REGISTRATION: {
    code: "DUPLICATE_REGISTRATION",
    httpStatus: 409,
    message: "Duplicate registration",
    userMessage: "既に申し込み済みです。",
    typeUri: `${BASE_URI}/duplicate-registration`,
    severity: "medium",
    retryable: false,
    category: "business",
  },
  ATTENDANCE_NOT_FOUND: {
    code: "ATTENDANCE_NOT_FOUND",
    httpStatus: 404,
    message: "Attendance record not found",
    userMessage: "参加データが見つかりません。",
    typeUri: `${BASE_URI}/attendance-not-found`,
    severity: "medium",
    retryable: false,
    category: "business",
  },
  ATTENDANCE_CAPACITY_REACHED: {
    code: "ATTENDANCE_CAPACITY_REACHED",
    httpStatus: 409,
    message: "Capacity reached for status change",
    userMessage: "定員に達しているため、ステータスを変更できません。",
    typeUri: `${BASE_URI}/attendance-capacity-reached`,
    severity: "medium",
    retryable: false,
    category: "business",
  },
  ATTENDANCE_DEADLINE_PASSED: {
    code: "ATTENDANCE_DEADLINE_PASSED",
    httpStatus: 410,
    message: "Attendance modification deadline passed",
    userMessage: "変更期限を過ぎているため操作できません。",
    typeUri: `${BASE_URI}/attendance-deadline-passed`,
    severity: "medium",
    retryable: false,
    category: "business",
  },
  ATTENDANCE_STATUS_ALREADY_UPDATED: {
    code: "ATTENDANCE_STATUS_ALREADY_UPDATED",
    httpStatus: 409,
    message: "Status already updated",
    userMessage: "ステータスは既に更新されています。",
    typeUri: `${BASE_URI}/attendance-status-already-updated`,
    severity: "low",
    retryable: false,
    category: "business",
  },
  ATTENDANCE_STATUS_ROLLBACK_REJECTED: {
    code: "ATTENDANCE_STATUS_ROLLBACK_REJECTED",
    httpStatus: 400,
    message: "Cannot rollback status",
    userMessage: "ステータスを過去の状態に戻すことはできません。",
    typeUri: `${BASE_URI}/attendance-status-rollback-rejected`,
    severity: "medium",
    retryable: false,
    category: "business",
  },
  GUEST_ATTENDANCE_UPDATE_ERROR: {
    code: "GUEST_ATTENDANCE_UPDATE_ERROR",
    httpStatus: 500,
    message: "Guest attendance update failed",
    userMessage: "参加情報の更新中にエラーが発生しました。",
    typeUri: `${BASE_URI}/guest-attendance-error`,
    severity: "high",
    retryable: true,
    category: "business",
  },

  // --- 決済 ---
  PAYMENT_FAILED: {
    code: "PAYMENT_FAILED",
    httpStatus: 402,
    message: "Payment failed",
    userMessage: "決済に失敗しました。別のカードをお試しください。",
    typeUri: `${BASE_URI}/payment-failed`,
    severity: "medium",
    retryable: false,
    category: "payment",
  },
  PAYMENT_PROCESSING_ERROR: {
    code: "PAYMENT_PROCESSING_ERROR",
    httpStatus: 422,
    message: "Error during payment processing",
    userMessage: "決済処理中にエラーが発生しました。しばらく待ってから再度お試しください。",
    typeUri: `${BASE_URI}/payment-processing-error`,
    severity: "high",
    retryable: true,
    category: "payment",
  },
  PAYMENT_SESSION_NOT_FOUND: {
    code: "PAYMENT_SESSION_NOT_FOUND",
    httpStatus: 404,
    message: "Payment session not found",
    userMessage: "決済セッションが見つかりません。",
    typeUri: `${BASE_URI}/payment-session-not-found`,
    severity: "medium",
    retryable: false,
    category: "payment",
  },
  PAYMENT_SESSION_OUTDATED: {
    code: "PAYMENT_SESSION_OUTDATED",
    httpStatus: 409,
    message: "Payment session is outdated",
    userMessage: "決済セッションの有効期限が切れています。最初からやり直してください。",
    typeUri: `${BASE_URI}/payment-session-outdated`,
    severity: "medium",
    retryable: false,
    category: "payment",
  },
  PAYMENT_SESSION_CREATION_FAILED: {
    code: "PAYMENT_SESSION_CREATION_FAILED",
    httpStatus: 500,
    message: "Payment session creation failed",
    userMessage: "決済セッションの作成に失敗しました。しばらくしてから再度お試しください。",
    typeUri: `${BASE_URI}/payment-session-creation-failed`,
    severity: "high",
    retryable: true,
    category: "payment",
  },
  PAYMENT_SESSION_REGISTRATION_FAILED: {
    code: "PAYMENT_SESSION_REGISTRATION_FAILED",
    httpStatus: 500,
    message: "PaymentService registration failed",
    userMessage: "決済サービスの初期化に失敗しました。",
    typeUri: `${BASE_URI}/payment-service-error`,
    severity: "critical",
    retryable: true,
    category: "payment",
  },
  PAYMENT_COMPLETION_NOTIFICATION_FAILED: {
    code: "PAYMENT_COMPLETION_NOTIFICATION_FAILED",
    httpStatus: 500,
    message: "Failed to send payment completion notification",
    userMessage: "決済完了通知の送信に失敗しました。",
    typeUri: `${BASE_URI}/payment-notification-error`,
    severity: "high",
    retryable: true,
    category: "payment",
  },
  INSUFFICIENT_BALANCE: {
    code: "INSUFFICIENT_BALANCE",
    httpStatus: 402,
    message: "Insufficient balance",
    userMessage: "カード残高不足のため決済できません。",
    typeUri: `${BASE_URI}/insufficient-balance`,
    severity: "medium",
    retryable: false,
    category: "payment",
  },
  CARD_ERROR: {
    code: "CARD_ERROR",
    httpStatus: 402,
    message: "Card error",
    userMessage: "カードエラーが発生しました。カード情報をご確認ください。",
    typeUri: `${BASE_URI}/card-error`,
    severity: "medium",
    retryable: false,
    category: "payment",
  },
  SETTLEMENT_REPORT_FAILED: {
    code: "SETTLEMENT_REPORT_FAILED",
    httpStatus: 500,
    message: "Settlement report generation failed",
    userMessage: "精算レポートの生成に失敗しました。",
    typeUri: `${BASE_URI}/settlement-report-failed`,
    severity: "high",
    retryable: true,
    category: "payment",
  },
  SETTLEMENT_REGENERATE_FAILED: {
    code: "SETTLEMENT_REGENERATE_FAILED",
    httpStatus: 500,
    message: "Failed to regenerate settlement report",
    userMessage: "精算レポートの再生成に失敗しました。",
    typeUri: `${BASE_URI}/settlement-regenerate-failed`,
    severity: "high",
    retryable: true,
    category: "payment",
  },

  // --- Stripe Connect ---
  CONNECT_ACCOUNT_NOT_FOUND: {
    code: "CONNECT_ACCOUNT_NOT_FOUND",
    httpStatus: 422,
    message: "Connect account not found",
    userMessage: "主催者の決済アカウントが見つかりません。",
    typeUri: `${BASE_URI}/connect-account-not-found`,
    severity: "high",
    retryable: false,
    category: "payment",
  },
  CONNECT_ACCOUNT_RESTRICTED: {
    code: "CONNECT_ACCOUNT_RESTRICTED",
    httpStatus: 422,
    message: "Connect account restricted",
    userMessage: "主催者の決済アカウントに制限がかかっています。",
    typeUri: `${BASE_URI}/connect-account-restricted`,
    severity: "high",
    retryable: false,
    category: "payment",
  },
  STRIPE_CONFIG_ERROR: {
    code: "STRIPE_CONFIG_ERROR",
    httpStatus: 500,
    message: "Stripe configuration error",
    userMessage: "決済システムの構成エラーが発生しました。",
    typeUri: `${BASE_URI}/stripe-config-error`,
    severity: "critical",
    retryable: false,
    category: "system",
  },
  STRIPE_CONNECT_SERVICE_ERROR: {
    code: "STRIPE_CONNECT_SERVICE_ERROR",
    httpStatus: 502,
    message: "Stripe Connect service operation failed",
    userMessage: "Stripe Connect連携処理でエラーが発生しました。",
    typeUri: `${BASE_URI}/stripe-connect-service-error`,
    severity: "high",
    retryable: true,
    category: "external",
  },
  STRIPE_CHECKOUT_SESSION_EXPIRED_UPDATE_FAILED: {
    code: "STRIPE_CHECKOUT_SESSION_EXPIRED_UPDATE_FAILED",
    httpStatus: 500,
    message: "Failed to update payment on expired session",
    userMessage: "セッション期限切れ処理に失敗しました。",
    typeUri: `${BASE_URI}/stripe-session-expired-error`,
    severity: "high",
    retryable: true,
    category: "payment",
  },

  // --- Webhook ---
  WEBHOOK_SIGNATURE_VERIFICATION_FAILED: {
    code: "WEBHOOK_SIGNATURE_VERIFICATION_FAILED",
    httpStatus: 400,
    message: "Webhook signature verification failed",
    userMessage: "Webhook署名の検証に失敗しました。",
    typeUri: `${BASE_URI}/webhook-signature-failed`,
    severity: "medium",
    retryable: false,
    category: "system",
  },
  WEBHOOK_SYNC_PROCESSING_FAILED: {
    code: "WEBHOOK_SYNC_PROCESSING_FAILED",
    httpStatus: 500,
    message: "Webhook sync processing failed",
    userMessage: "Webhook同期処理に失敗しました。",
    typeUri: `${BASE_URI}/webhook-sync-failed`,
    severity: "high",
    retryable: true,
    category: "system",
  },
  WEBHOOK_QSTASH_FORWARDING_FAILED: {
    code: "WEBHOOK_QSTASH_FORWARDING_FAILED",
    httpStatus: 500,
    message: "QStash forwarding failed",
    userMessage: "Webhook転送に失敗しました。",
    typeUri: `${BASE_URI}/webhook-forwarding-failed`,
    severity: "critical",
    retryable: true,
    category: "system",
  },
  WEBHOOK_CONFIG_ERROR: {
    code: "WEBHOOK_CONFIG_ERROR",
    httpStatus: 500,
    message: "Webhook configuration error",
    userMessage: "Webhook設定エラーが発生しました。",
    typeUri: `${BASE_URI}/webhook-config-error`,
    severity: "critical",
    retryable: false,
    category: "system",
  },
  WEBHOOK_UNEXPECTED_ERROR: {
    code: "WEBHOOK_UNEXPECTED_ERROR",
    httpStatus: 500,
    message: "Unexpected error in webhook processing",
    userMessage: "Webhook処理中に予期しないエラーが発生しました。",
    typeUri: `${BASE_URI}/webhook-error`,
    severity: "critical",
    retryable: true,
    category: "system",
  },
  WEBHOOK_PAYMENT_NOT_FOUND: {
    code: "WEBHOOK_PAYMENT_NOT_FOUND",
    httpStatus: 404,
    message: "Payment record not found for webhook",
    userMessage: "決済レコードが見つかりません。",
    typeUri: `${BASE_URI}/webhook-payment-not-found`,
    severity: "high",
    retryable: false,
    category: "payment",
  },
  WEBHOOK_INVALID_PAYLOAD: {
    code: "WEBHOOK_INVALID_PAYLOAD",
    httpStatus: 400,
    message: "Invalid webhook payload",
    userMessage: "Webhookペイロードが不正です。",
    typeUri: `${BASE_URI}/webhook-invalid-payload`,
    severity: "medium",
    retryable: false,
    category: "validation",
  },
  WEBHOOK_DUPLICATE_EVENT: {
    code: "WEBHOOK_DUPLICATE_EVENT",
    httpStatus: 200, // 成功扱い(Idempotency)
    message: "Duplicate webhook event",
    userMessage: "重複したWebhookイベントです。",
    typeUri: `${BASE_URI}/webhook-duplicate`,
    severity: "low",
    retryable: false,
    category: "system",
  },
  CONNECT_WEBHOOK_ACCOUNT_UPDATED_ERROR: {
    code: "CONNECT_WEBHOOK_ACCOUNT_UPDATED_ERROR",
    httpStatus: 500,
    message: "Error handling Connect account.updated",
    userMessage: "Connectアカウント更新処理に失敗しました。",
    typeUri: `${BASE_URI}/connect-webhook-error`,
    severity: "high",
    retryable: true,
    category: "system",
  },
  CONNECT_WEBHOOK_DEAUTHORIZED_ERROR: {
    code: "CONNECT_WEBHOOK_DEAUTHORIZED_ERROR",
    httpStatus: 500,
    message: "Error handling Connect deauthorization",
    userMessage: "Connect連携解除処理に失敗しました。",
    typeUri: `${BASE_URI}/connect-webhook-deauth-error`,
    severity: "high",
    retryable: true,
    category: "system",
  },
  CONNECT_WEBHOOK_PAYOUT_ERROR: {
    code: "CONNECT_WEBHOOK_PAYOUT_ERROR",
    httpStatus: 500,
    message: "Error handling Connect payout",
    userMessage: "振込イベント処理に失敗しました。",
    typeUri: `${BASE_URI}/connect-webhook-payout-error`,
    severity: "high",
    retryable: true,
    category: "system",
  },
  CONNECT_WEBHOOK_NOTIFICATION_ERROR: {
    code: "CONNECT_WEBHOOK_NOTIFICATION_ERROR",
    httpStatus: 500,
    message: "Error sending Connect webhook notification",
    userMessage: "通知送信に失敗しました。",
    typeUri: `${BASE_URI}/connect-webhook-notification-error`,
    severity: "medium",
    retryable: true,
    category: "system",
  },

  // --- セキュリティ ---
  SUSPICIOUS_ACTIVITY: {
    code: "SUSPICIOUS_ACTIVITY",
    httpStatus: 403,
    message: "Suspicious activity detected",
    userMessage: "不正なアクセスが検出されました。",
    typeUri: `${BASE_URI}/suspicious-activity`,
    severity: "high",
    retryable: false,
    category: "security",
  },
  XSS_ATTEMPT: {
    code: "XSS_ATTEMPT",
    httpStatus: 403,
    message: "XSS attempt detected",
    userMessage: "不正な入力が検出されました。",
    typeUri: `${BASE_URI}/xss-attempt`,
    severity: "high",
    retryable: false,
    category: "security",
  },
  SECURITY_EVENT_DETECTED: {
    code: "SECURITY_EVENT_DETECTED",
    httpStatus: 403,
    message: "Security event detected",
    userMessage: "セキュリティイベントが検出されました。",
    typeUri: `${BASE_URI}/security-event`,
    severity: "high",
    retryable: false,
    category: "security",
  },
  ACCOUNT_LOCKOUT_SYSTEM_ERROR: {
    code: "ACCOUNT_LOCKOUT_SYSTEM_ERROR",
    httpStatus: 500,
    message: "Account lockout system failed",
    userMessage: "アカウントロックアウトシステムでエラーが発生しました。",
    typeUri: `${BASE_URI}/lockout-error`,
    severity: "high",
    retryable: true,
    category: "security",
  },

  // --- システム・基盤 ---
  INTERNAL_ERROR: {
    code: "INTERNAL_ERROR",
    httpStatus: 500,
    message: "Internal server error",
    userMessage: "システムエラーが発生しました。しばらく時間をおいて再度お試しください。",
    typeUri: `${BASE_URI}/internal-error`,
    severity: "high",
    retryable: true,
    category: "system",
  },
  DATABASE_ERROR: {
    code: "DATABASE_ERROR",
    httpStatus: 500,
    message: "Database error",
    userMessage: "データベースエラーが発生しました。",
    typeUri: `${BASE_URI}/database-error`,
    severity: "high",
    retryable: true,
    category: "system",
  },
  EXTERNAL_SERVICE_ERROR: {
    code: "EXTERNAL_SERVICE_ERROR",
    httpStatus: 502,
    message: "External service error",
    userMessage: "外部サービスとの通信でエラーが発生しました。",
    typeUri: `${BASE_URI}/external-service-error`,
    severity: "medium",
    retryable: true,
    category: "external",
  },
  RATE_LIMITED: {
    code: "RATE_LIMITED",
    httpStatus: 429,
    message: "Too many requests",
    userMessage: "リクエスト回数が多すぎます。しばらく時間をおいてから再度お試しください。",
    typeUri: `${BASE_URI}/rate-limited`,
    severity: "low",
    retryable: true,
    category: "system",
  },
  MAINTENANCE: {
    code: "MAINTENANCE",
    httpStatus: 503,
    message: "System under maintenance",
    userMessage: "現在メンテナンス中です。",
    typeUri: `${BASE_URI}/maintenance`,
    severity: "low",
    retryable: true,
    category: "system",
  },
  NETWORK_ERROR: {
    code: "NETWORK_ERROR",
    httpStatus: 0,
    message: "Network unreachable",
    userMessage: "ネットワーク接続を確認してください。",
    typeUri: `${BASE_URI}/network-error`,
    severity: "low",
    retryable: true,
    category: "system",
  },
  TIMEOUT_ERROR: {
    code: "TIMEOUT_ERROR",
    httpStatus: 504,
    message: "Request timed out",
    userMessage: "処理がタイムアウトしました。再度お試しください。",
    typeUri: `${BASE_URI}/timeout-error`,
    severity: "medium",
    retryable: true,
    category: "system",
  },
  ENV_VAR_MISSING: {
    code: "ENV_VAR_MISSING",
    httpStatus: 500,
    message: "Required environment variable is missing",
    userMessage: "システム設定エラーが発生しました。",
    typeUri: `${BASE_URI}/config-error`,
    severity: "critical",
    retryable: false,
    category: "system",
  },
  CRON_EXECUTION_ERROR: {
    code: "CRON_EXECUTION_ERROR",
    httpStatus: 500,
    message: "Cron job execution failed",
    userMessage: "定期実行ジョブでエラーが発生しました。",
    typeUri: `${BASE_URI}/cron-error`,
    severity: "medium",
    retryable: true,
    category: "system",
  },
  AUDIT_LOG_RECORDING_FAILED: {
    code: "AUDIT_LOG_RECORDING_FAILED",
    httpStatus: 500,
    message: "Failed to record audit log",
    userMessage: "監査ログの記録に失敗しました。",
    typeUri: `${BASE_URI}/audit-log-error`,
    severity: "medium",
    retryable: true,
    category: "system",
  },
  EMAIL_SENDING_FAILED: {
    code: "EMAIL_SENDING_FAILED",
    httpStatus: 500,
    message: "Failed to send email",
    userMessage: "メール送信に失敗しました。",
    typeUri: `${BASE_URI}/email-error`,
    severity: "medium",
    retryable: true,
    category: "system",
  },
  ADMIN_ALERT_FAILED: {
    code: "ADMIN_ALERT_FAILED",
    httpStatus: 500,
    message: "Failed to send admin alert",
    userMessage: "管理者への通知に失敗しました。",
    typeUri: `${BASE_URI}/admin-alert-error`,
    severity: "high",
    retryable: true,
    category: "system",
  },
  GA4_TRACKING_FAILED: {
    code: "GA4_TRACKING_FAILED",
    httpStatus: 500,
    message: "Failed to send GA4 event",
    userMessage: "GA4イベント送信に失敗しました。",
    typeUri: `${BASE_URI}/ga4-error`,
    severity: "medium",
    retryable: false,
    category: "system",
  },
  UNKNOWN_ERROR: {
    code: "UNKNOWN_ERROR",
    httpStatus: 500,
    message: "Unknown error occurred",
    userMessage: "予期せぬエラーが発生しました。",
    typeUri: `${BASE_URI}/unknown-error`,
    severity: "medium",
    retryable: true,
    category: "unknown",
  },
};
