-- Fix guest_token field in attendances table
-- Remove default value and ensure NOT NULL constraint
-- This migration ensures guest tokens are always generated by the application

-- First, update any existing records that might have NULL guest_token
-- (This should not happen in practice, but ensures data integrity)
UPDATE public.attendances 
SET guest_token = substring(md5(random()::text) from 1 for 32)
WHERE guest_token IS NULL;

-- Remove the default value from guest_token column
-- The application will be responsible for generating all guest tokens
ALTER TABLE public.attendances 
ALTER COLUMN guest_token DROP DEFAULT;

-- Ensure NOT NULL constraint is enforced
-- (It should already be NOT NULL due to the UNIQUE constraint, but make it explicit)
ALTER TABLE public.attendances 
ALTER COLUMN guest_token SET NOT NULL;

-- Add a comment to document the change
COMMENT ON COLUMN public.attendances.guest_token IS 'Guest access token generated by application (Base64 format, 32 characters)';