import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

import { assertLocalSupabaseUrl } from "./local-supabase-env";

/**
 * `db` / `integration` プロジェクトの実行前に1回だけ走らせる prepare コマンド。
 *
 * 1. ローカル Supabase スタックの状態を確認し、停止していれば起動する
 * 2. 対象がローカルスタックであることを検証する
 * 3. マイグレーションと seed を1回だけリセットする
 * 4. 接続情報を gitignore された生成ファイルへ書き出す
 *
 * Vitest の setupFiles / globalSetup からは呼ばない（DB ライフサイクルは本コマンドの責務）。
 */

const GENERATED_ENV_PATH = fileURLToPath(new URL("../.env.local-supabase", import.meta.url));
const RELATIVE_ENV_PATH = "tests/.env.local-supabase";

const REQUIRED_KEYS = [
  "NEXT_PUBLIC_SUPABASE_URL",
  "NEXT_PUBLIC_SUPABASE_ANON_KEY",
  "SUPABASE_SERVICE_ROLE_KEY",
] as const;

/** CLI としての進捗表示。テストランナーのログではないため stdout へ直接書く。 */
function log(message: string): void {
  process.stdout.write(`${message}\n`);
}

/**
 * `supabase status -o env` の出力名を、アプリと同じ環境変数名へ揃える。
 *
 * 既定の出力名は `API_URL` / `ANON_KEY` / `SERVICE_ROLE_KEY`。
 * ここで override しない `PUBLISHABLE_KEY`（`sb_publishable_…`）と
 * `SECRET_KEY`（`sb_secret_…`）は新形式の別キーであり、allowlist 抽出で除外される。
 */
const STATUS_ARGS = [
  "exec",
  "supabase",
  "status",
  "-o",
  "env",
  "--override-name",
  "api.url=NEXT_PUBLIC_SUPABASE_URL",
  "--override-name",
  "auth.anon_key=NEXT_PUBLIC_SUPABASE_ANON_KEY",
  "--override-name",
  "auth.service_role_key=SUPABASE_SERVICE_ROLE_KEY",
];

function stripQuotes(value: string): string {
  const first = value[0];
  if ((first === '"' || first === "'") && value.length >= 2 && value.at(-1) === first) {
    return value.slice(1, -1);
  }
  return value;
}

function parseEnvOutput(stdout: string): Map<string, string> {
  const entries = new Map<string, string>();

  for (const rawLine of stdout.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (line === "" || line.startsWith("#")) continue;

    const separatorIndex = line.indexOf("=");
    if (separatorIndex <= 0) continue;

    const key = line.slice(0, separatorIndex).trim();
    // CLI の告知メッセージ（"A new version of Supabase CLI is available: ..." 等）を弾く
    if (!/^[A-Z][A-Z0-9_]*$/.test(key)) continue;

    entries.set(key, stripQuotes(line.slice(separatorIndex + 1).trim()));
  }

  return entries;
}

/**
 * スタックの状態を取得する。
 *
 * 停止時は `supabase status` が非 0 で終了するが、一部サービスのみ停止している場合は
 * exit 0 のまま接続情報を返す。exit code は判定に使わず、3キーが揃うかどうかで判断する。
 */
function readStatus(): Map<string, string> | null {
  let stdout: string;
  try {
    stdout = execFileSync("pnpm", STATUS_ARGS, {
      encoding: "utf8",
      stdio: ["ignore", "pipe", "pipe"],
    });
  } catch (error) {
    const captured = (error as { stdout?: string }).stdout;
    if (typeof captured !== "string") return null;
    stdout = captured;
  }

  const entries = parseEnvOutput(stdout);
  const hasAllKeys = REQUIRED_KEYS.every((key) => Boolean(entries.get(key)));

  return hasAllKeys ? entries : null;
}

function run(args: string[]): void {
  execFileSync("pnpm", ["exec", "supabase", ...args], { stdio: "inherit" });
}

function assertLocalDbUrl(dbUrl: string): void {
  // `db reset` が実際に触るのは API ではなく DB のため、DB_URL も個別に検証する。
  let host: string;
  try {
    host = new URL(dbUrl).hostname;
  } catch {
    throw new Error(`supabase status -o env の DB_URL が URL として不正です: ${dbUrl}`);
  }

  if (host !== "localhost" && host !== "127.0.0.1") {
    throw new Error(
      `supabase status -o env の DB_URL がローカルスタックを指していません（host: ${host}）。` +
        `prepare はローカル Supabase に対してのみ実行できます。`
    );
  }
}

function writeGeneratedEnv(entries: Map<string, string>): void {
  const lines = [
    "# Generated by `pnpm test:db:prepare`. Do not edit.",
    ...REQUIRED_KEYS.map((key) => `${key}="${entries.get(key) as string}"`),
    "",
  ];

  // service_role キーを含むため、所有者のみ読み書き可能にする。
  writeFileSync(GENERATED_ENV_PATH, lines.join("\n"), { encoding: "utf8", mode: 0o600 });
}

function main(): void {
  let entries = readStatus();

  if (entries === null) {
    log("ローカル Supabase スタックが起動していません。`supabase start` を実行します。");
    run(["start"]);

    entries = readStatus();
    if (entries === null) {
      throw new Error(
        "`supabase start` の後もローカル Supabase の接続情報を取得できませんでした。" +
          "`pnpm exec supabase status` の出力を確認してください。"
      );
    }
  }

  assertLocalSupabaseUrl(
    entries.get("NEXT_PUBLIC_SUPABASE_URL") as string,
    "supabase status -o env"
  );

  const dbUrl = entries.get("DB_URL");
  if (!dbUrl) {
    throw new Error("supabase status -o env の出力に DB_URL がありません。");
  }
  assertLocalDbUrl(dbUrl);

  // config.toml の [db.migrations] / [db.seed] がいずれも有効なため、
  // `db reset` 1回でマイグレーションと seed の両方が適用される。
  log("ローカル Supabase をリセットします（migrations + seed）。");
  run(["db", "reset"]);

  // リセット成功後に書き出す。生成ファイルの存在が prepare 完了の signal であり、
  // リセット失敗時に残すと壊れた DB に対してテストが走ってしまう。
  writeGeneratedEnv(entries);

  log(`ローカル Supabase の接続情報を ${RELATIVE_ENV_PATH} へ書き出しました。`);
}

main();
