name: Send Reminders

on:
  schedule:
    - cron: "0 0 * * *" # 毎日 UTC 0:00 (JST 9:00)
  workflow_dispatch: # 手動実行を許可

jobs:
  send-reminders:
    runs-on: ubuntu-latest
    steps:
      - name: Send Reminders
        run: |
          response=$(curl -s -w "\n%{http_code}" -X GET \
            "${{ secrets.APP_URL }}/api/cron/send-reminders" \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}")
          http_code=$(echo "$response" | tail -n1)
          body=$(echo "$response" | sed '$d')
          echo "Response: $body"
          if [ "$http_code" -ne 200 ]; then
            echo "Error: HTTP $http_code"
            exit 1
          fi
